import { Section, SectionBounds } from '@/types';

const SEAT_SIZE = 30;

export const getSectionsBounds = (sections: Section[]): SectionBounds[] =>
  sections.map(section => {
    const { rows } = section;

    if (!rows.length) {
      return { x: section.transform.x, y: section.transform.y, width: 0, height: 0, section };
    }

    // Optimize: Get dimensions directly from first/last rows/seats
    // Assumption: Sections are rectangular (generated by venue.js logic)
    const firstRow = rows[0];
    const lastRow = rows[rows.length - 1];

    if (!firstRow.seats.length || !lastRow.seats.length) {
      return { x: section.transform.x, y: section.transform.y, width: 0, height: 0, section };
    }

    // Calculate bounds using only corner seats
    // This avoids iterating over thousands of seats (O(1) vs O(N))
    const firstSeat = firstRow.seats[0];
    const lastSeat = firstRow.seats[firstRow.seats.length - 1];

    const minX = firstSeat.x;
    const maxX = lastSeat.x;
    const minY = firstSeat.y;
    const maxY = lastRow.seats[0].y;

    const scale = section.transform.scale || 1;

    // Calculate final dimensions
    const width = (maxX - minX + SEAT_SIZE) * scale;
    const height = (maxY - minY + SEAT_SIZE) * scale;
    const x = section.transform.x + minX * scale;
    const y = section.transform.y + minY * scale;

    return { x, y, width, height, section };
  });
